### ISSUE TITLE
OutOfMemoryError thrown during large batch upload

### ISSUE THREAD

**Issue by gwinstanley** [holmbergius/Wildbook#53]
Current implementation of batch upload module (only available in _mantamatcher.org_ branch for now) throws an OutOfMemoryError during image thumbnail processing phase. As this is the last phase, the data has already been committed to the database, so it's non-critical in terms of data integrity, but it leaves encounter thumbnails unassigned (therefore needing to be reset), and individual watermarked image versions ungenerated (these will be automatically regenerated, but show as unavailable initially). Recommend that batch upload module stay in pre-release (and only admin-accessible) for now until this can be resolved.

The issue seems to relate to memory leaks in the Java ImageIO subsystem, which are only evident with intensive repetitive image operations, but might be relevant to other sporadic memory leaks that have arisen.

Possible fixes already attempted, none of which have worked so far:
1. Explicitly resetting ImageIO ImageReader/Writer before each use (shouldn't be necessary, but possible bug listed in older Java versions).
2. Entirely avoid reuse of ImageIO ImageReader/Writer.
3. Replacement of standard ImageIO JPEG plugin with 3rd-party plugin ([TwelveMonkeys](https://github.com/haraldk/TwelveMonkeys)).

Attempt 3 needs to be tried again, checking that the external plugin isn't delegating to standard code, which is implied by the following stacktrace:
```
java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:58) ~[na:1.6.0_21]
        at java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:397) ~[na:1.6.0_21]
        at java.awt.image.Raster.createWritableRaster(Raster.java:938) ~[na:1.6.0_21]
        at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1056) ~[na:1.6.0_21]
        at javax.imageio.ImageReader.getDestination(ImageReader.java:2879) ~[na:1.6.0_21]
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:925) ~[na:1.6.0_21]
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:897) ~[na:1.6.0_21]
        at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source) ~[imageio-jpeg-3.0-rc5.jar:3.0-rc5]
        at javax.imageio.ImageIO.read(ImageIO.java:1422) ~[na:1.6.0_21]
        at javax.imageio.ImageIO.read(ImageIO.java:1282) ~[na:1.6.0_21]
        at org.ecocean.util.MediaUtilities.loadImage(MediaUtilities.java:177) ~[MediaUtilities.class:na]
        at org.ecocean.util.MediaUtilities.loadImageAsSRGB(MediaUtilities.java:216) ~[MediaUtilities.class:na]
        at org.ecocean.batch.BatchProcessor.createThumbnail(BatchProcessor.java:669) ~[BatchProcessor.class:na]
        at org.ecocean.batch.BatchProcessor.run(BatchProcessor.java:584) ~[BatchProcessor.class:na]
```

**Comment by gwinstanley** [comment]
Closing this issue, as seems to be stable after increasing VM heap size.
