### ISSUE TITLE
5.4.0 release NullPointerException when using with mySQL

### ISSUE THREAD

**Issue by Carcahrodon** [holmbergius/Wildbook#65]
When deploying the prepackaged war file from the wildbook website, Wildbook loads fine if using the default derby database. However, if I go into jdoconfig.properties and change it to use mySQL instead, I'll get a fatal error when loading the project. Here is the log file:

Oct 25, 2015 11:19:56 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/wildbook-5.4.0-RELEASE] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at org.ecocean.Shepherd.<init>(Shepherd.java:80)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:103)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ecocean.servlet.StrutsUTF8Filter.doFilter(StrutsUTF8Filter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

 This is the line in org.ecocean.Shepherd that's referenced (80):
       this.pm = ShepherdPMF.getPMF(this.localContext).getPersistenceManager();

I've got mysql-connector-java-5.1.8-bin.jar in the <install dir>/WEB-INF/lib directory, I'm using mySQL 5.6.27, Tomcat 7.0.65, JDK 1.7_u71, I've made user shepherd and password shepherd on mySQL.

**Comment by gforghetti** [comment]
I have hit this same problem also.

**Comment by RichardJune** [comment]
Gary, feel free to contact me at 503-545-7745 or holmbergius@gmail.com

We have been running several projects on MySQL (flukebook.org) but just
converted to PostgreSQL and could also share an Amazon VM for your
experimentation and use. What species are you working on?

Jason Holmberg
Wildbook for Whale Sharks
http://www.whaleshark.org

**Comment by holmbergius** [comment]
Gary, feel free to contact me at 503-545-7745 or holmbergius@gmail.com

We have been running several projects on MySQL (flukebook.org) but just
converted to PostgreSQL and could also share an Amazon VM for your
experimentation and use. What species are you working on?

Jason Holmberg
Wildbook for Whale Sharks
http://www.whaleshark.org
